<datalist id='universities'>
  <select id = 'universities-select'>
    <option value="Bucknell University">Bucknell University</option>
    <option value="Cedarville University">Cedarville University</option>
    <option value="Cleveland State University">Cleveland State University</option>
    <option value="DeVry University, Columbus Campus">DeVry University, Columbus Campus</option>
    <option value="DeVry University, Online">DeVry University, Online</option>
    <option value="Drexel University">Drexel University</option>
    <option value="Gannon University">Gannon University</option>
	<option value="George Washington University">George Washington University</option>
    <option value="Lafayette College">Lafayette College</option>
    <option value="Montgomery College">Montgomery College</option>
    <option value="Ohio Northern University">Ohio Northern University</option>
    <option value="Ohio State University">Ohio State University</option>
    <!--option value="Penn State">Penn State</option--><!--DUPLICATE-->
    <option value="Pennsylvania College of Technology">Pennsylvania College of Technology</option>
    <option value="Pennsylvania State University">Pennsylvania State University</option>
    <option value="Pennsylvania State University, Abington">Pennsylvania State University, Abington</option>
    <option value="Pennsylvania State University, Harrisburg">Pennsylvania State University, Harrisburg</option>
    <option value="Rowan University">Rowan University</option>
    <option value="Shepherd University">Shepherd University</option>
    <option value="Temple University">Temple University</option>
    <option value="The University of Akron">The University of Akron</option>
    <option value="University of Cincinnati">University of Cincinnati</option>
    <option value="University of Dayton">University of Dayton</option>
    <option value="University of Delaware">University of Delaware</option>
    <option value="University of Maryland">University of Maryland</option>
    <option value="University of Maryland, Baltimore County">University of Maryland, Baltimore County</option>
    <option value="University of Pittsburgh">University of Pittsburgh</option>
    <option value="University of Scranton">University of Scranton</option>
    <option value="University of the District of Columbia">University of the District of Columbia</option>
    <option value="Villanova University">Villanova University</option>
    <option value="West Virginia Institute of Technology">West Virginia Institute of Technology</option>
    <option value="West Virginia University">West Virginia University</option>
    <option value="Wright State University">Wright State University</option>
    <option value="Youngstown State University">Youngstown State University</option>
  </select>
</datalist>
